import React from 'react'
import Style from './Layout.module.css'
import Head from 'next/head'
import NavBar from '../NavBar/NavBar'
import Home from '../Home/Home'

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>Esc. Tenica 32 "Gral. Jose de San Martin" {title ? `| ${title}` : ''} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
     <Home/>
      <div className={Style.container}>
        {children}
      </div>
    </>
  )
}

export default Layout