import React from 'react'
import Style from './Layout.module.css'
import Head from 'next/head'
import NavBar from '../NavBar/NavBar'

const Layout = ({ children, title, favicon, page }) => {
  return (
    <>
      <Head>
        <title> {title ? `${title}` : ''} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={favicon ? favicon : '/favicon2.ico'} />
      </Head>
      <NavBar page={page} />
      <div className={Style.container}>
        {children}
      </div>
    </>
  )
}

export default Layout